#pragma once

// Must stay in the same order as the stubs in winmm_exports.asm
#define WINMM_EXPORTS(X) \
  X(mciExecute, 3) \
  X(CloseDriver, 4) \
  X(DefDriverProc, 5) \
  X(DriverCallback, 6) \
  X(DrvGetModuleHandle, 7) \
  X(GetDriverModuleHandle, 8) \
  X(OpenDriver, 9) \
  X(PlaySound, 10) \
  X(PlaySoundA, 11) \
  X(PlaySoundW, 12) \
  X(SendDriverMessage, 13) \
  X(WOWAppExit, 14) \
  X(auxGetDevCapsA, 15) \
  X(auxGetDevCapsW, 16) \
  X(auxGetNumDevs, 17) \
  X(auxGetVolume, 18) \
  X(auxOutMessage, 19) \
  X(auxSetVolume, 20) \
  X(joyConfigChanged, 21) \
  X(joyGetDevCapsA, 22) \
  X(joyGetDevCapsW, 23) \
  X(joyGetNumDevs, 24) \
  X(joyGetPos, 25) \
  X(joyGetPosEx, 26) \
  X(joyGetThreshold, 27) \
  X(joyReleaseCapture, 28) \
  X(joySetCapture, 29) \
  X(joySetThreshold, 30) \
  X(mciDriverNotify, 31) \
  X(mciDriverYield, 32) \
  X(mciFreeCommandResource, 33) \
  X(mciGetCreatorTask, 34) \
  X(mciGetDeviceIDA, 35) \
  X(mciGetDeviceIDFromElementIDA, 36) \
  X(mciGetDeviceIDFromElementIDW, 37) \
  X(mciGetDeviceIDW, 38) \
  X(mciGetDriverData, 39) \
  X(mciGetErrorStringA, 40) \
  X(mciGetErrorStringW, 41) \
  X(mciGetYieldProc, 42) \
  X(mciLoadCommandResource, 43) \
  X(mciSendCommandA, 44) \
  X(mciSendCommandW, 45) \
  X(mciSendStringA, 46) \
  X(mciSendStringW, 47) \
  X(mciSetDriverData, 48) \
  X(mciSetYieldProc, 49) \
  X(midiConnect, 50) \
  X(midiDisconnect, 51) \
  X(midiInAddBuffer, 52) \
  X(midiInClose, 53) \
  X(midiInGetDevCapsA, 54) \
  X(midiInGetDevCapsW, 55) \
  X(midiInGetErrorTextA, 56) \
  X(midiInGetErrorTextW, 57) \
  X(midiInGetID, 58) \
  X(midiInGetNumDevs, 59) \
  X(midiInMessage, 60) \
  X(midiInOpen, 61) \
  X(midiInPrepareHeader, 62) \
  X(midiInReset, 63) \
  X(midiInStart, 64) \
  X(midiInStop, 65) \
  X(midiInUnprepareHeader, 66) \
  X(midiOutCacheDrumPatches, 67) \
  X(midiOutCachePatches, 68) \
  X(midiOutClose, 69) \
  X(midiOutGetDevCapsA, 70) \
  X(midiOutGetDevCapsW, 71) \
  X(midiOutGetErrorTextA, 72) \
  X(midiOutGetErrorTextW, 73) \
  X(midiOutGetID, 74) \
  X(midiOutGetNumDevs, 75) \
  X(midiOutGetVolume, 76) \
  X(midiOutLongMsg, 77) \
  X(midiOutMessage, 78) \
  X(midiOutOpen, 79) \
  X(midiOutPrepareHeader, 80) \
  X(midiOutReset, 81) \
  X(midiOutSetVolume, 82) \
  X(midiOutShortMsg, 83) \
  X(midiOutUnprepareHeader, 84) \
  X(midiStreamClose, 85) \
  X(midiStreamOpen, 86) \
  X(midiStreamOut, 87) \
  X(midiStreamPause, 88) \
  X(midiStreamPosition, 89) \
  X(midiStreamProperty, 90) \
  X(midiStreamRestart, 91) \
  X(midiStreamStop, 92) \
  X(mixerClose, 93) \
  X(mixerGetControlDetailsA, 94) \
  X(mixerGetControlDetailsW, 95) \
  X(mixerGetDevCapsA, 96) \
  X(mixerGetDevCapsW, 97) \
  X(mixerGetID, 98) \
  X(mixerGetLineControlsA, 99) \
  X(mixerGetLineControlsW, 100) \
  X(mixerGetLineInfoA, 101) \
  X(mixerGetLineInfoW, 102) \
  X(mixerGetNumDevs, 103) \
  X(mixerMessage, 104) \
  X(mixerOpen, 105) \
  X(mixerSetControlDetails, 106) \
  X(mmDrvInstall, 107) \
  X(mmGetCurrentTask, 108) \
  X(mmTaskBlock, 109) \
  X(mmTaskCreate, 110) \
  X(mmTaskSignal, 111) \
  X(mmTaskYield, 112) \
  X(mmioAdvance, 113) \
  X(mmioAscend, 114) \
  X(mmioClose, 115) \
  X(mmioCreateChunk, 116) \
  X(mmioDescend, 117) \
  X(mmioFlush, 118) \
  X(mmioGetInfo, 119) \
  X(mmioInstallIOProcA, 120) \
  X(mmioInstallIOProcW, 121) \
  X(mmioOpenA, 122) \
  X(mmioOpenW, 123) \
  X(mmioRead, 124) \
  X(mmioRenameA, 125) \
  X(mmioRenameW, 126) \
  X(mmioSeek, 127) \
  X(mmioSendMessage, 128) \
  X(mmioSetBuffer, 129) \
  X(mmioSetInfo, 130) \
  X(mmioStringToFOURCCA, 131) \
  X(mmioStringToFOURCCW, 132) \
  X(mmioWrite, 133) \
  X(mmsystemGetVersion, 134) \
  X(sndPlaySoundA, 135) \
  X(sndPlaySoundW, 136) \
  X(timeBeginPeriod, 137) \
  X(timeEndPeriod, 138) \
  X(timeGetDevCaps, 139) \
  X(timeGetSystemTime, 140) \
  X(timeGetTime, 141) \
  X(timeKillEvent, 142) \
  X(timeSetEvent, 143) \
  X(waveInAddBuffer, 144) \
  X(waveInClose, 145) \
  X(waveInGetDevCapsA, 146) \
  X(waveInGetDevCapsW, 147) \
  X(waveInGetErrorTextA, 148) \
  X(waveInGetErrorTextW, 149) \
  X(waveInGetID, 150) \
  X(waveInGetNumDevs, 151) \
  X(waveInGetPosition, 152) \
  X(waveInMessage, 153) \
  X(waveInOpen, 154) \
  X(waveInPrepareHeader, 155) \
  X(waveInReset, 156) \
  X(waveInStart, 157) \
  X(waveInStop, 158) \
  X(waveInUnprepareHeader, 159) \
  X(waveOutBreakLoop, 160) \
  X(waveOutClose, 161) \
  X(waveOutGetDevCapsA, 162) \
  X(waveOutGetDevCapsW, 163) \
  X(waveOutGetErrorTextA, 164) \
  X(waveOutGetErrorTextW, 165) \
  X(waveOutGetID, 166) \
  X(waveOutGetNumDevs, 167) \
  X(waveOutGetPitch, 168) \
  X(waveOutGetPlaybackRate, 169) \
  X(waveOutGetPosition, 170) \
  X(waveOutGetVolume, 171) \
  X(waveOutMessage, 172) \
  X(waveOutOpen, 173) \
  X(waveOutPause, 174) \
  X(waveOutPrepareHeader, 175) \
  X(waveOutReset, 176) \
  X(waveOutRestart, 177) \
  X(waveOutSetPitch, 178) \
  X(waveOutSetPlaybackRate, 179) \
  X(waveOutSetVolume, 180) \
  X(waveOutUnprepareHeader, 181) \
  X(waveOutWrite, 182)
