EXTERN g_winmm:QWORD

slot = 0

stub MACRO name
PUBLIC name
name PROC
  jmp qword ptr [g_winmm + 8 * slot]
name ENDP
slot = slot + 1
ENDM

.code
stub mciExecute
stub CloseDriver
stub DefDriverProc
stub DriverCallback
stub DrvGetModuleHandle
stub GetDriverModuleHandle
stub OpenDriver
stub PlaySound
stub PlaySoundA
stub PlaySoundW
stub SendDriverMessage
stub WOWAppExit
stub auxGetDevCapsA
stub auxGetDevCapsW
stub auxGetNumDevs
stub auxGetVolume
stub auxOutMessage
stub auxSetVolume
stub joyConfigChanged
stub joyGetDevCapsA
stub joyGetDevCapsW
stub joyGetNumDevs
stub joyGetPos
stub joyGetPosEx
stub joyGetThreshold
stub joyReleaseCapture
stub joySetCapture
stub joySetThreshold
stub mciDriverNotify
stub mciDriverYield
stub mciFreeCommandResource
stub mciGetCreatorTask
stub mciGetDeviceIDA
stub mciGetDeviceIDFromElementIDA
stub mciGetDeviceIDFromElementIDW
stub mciGetDeviceIDW
stub mciGetDriverData
stub mciGetErrorStringA
stub mciGetErrorStringW
stub mciGetYieldProc
stub mciLoadCommandResource
stub mciSendCommandA
stub mciSendCommandW
stub mciSendStringA
stub mciSendStringW
stub mciSetDriverData
stub mciSetYieldProc
stub midiConnect
stub midiDisconnect
stub midiInAddBuffer
stub midiInClose
stub midiInGetDevCapsA
stub midiInGetDevCapsW
stub midiInGetErrorTextA
stub midiInGetErrorTextW
stub midiInGetID
stub midiInGetNumDevs
stub midiInMessage
stub midiInOpen
stub midiInPrepareHeader
stub midiInReset
stub midiInStart
stub midiInStop
stub midiInUnprepareHeader
stub midiOutCacheDrumPatches
stub midiOutCachePatches
stub midiOutClose
stub midiOutGetDevCapsA
stub midiOutGetDevCapsW
stub midiOutGetErrorTextA
stub midiOutGetErrorTextW
stub midiOutGetID
stub midiOutGetNumDevs
stub midiOutGetVolume
stub midiOutLongMsg
stub midiOutMessage
stub midiOutOpen
stub midiOutPrepareHeader
stub midiOutReset
stub midiOutSetVolume
stub midiOutShortMsg
stub midiOutUnprepareHeader
stub midiStreamClose
stub midiStreamOpen
stub midiStreamOut
stub midiStreamPause
stub midiStreamPosition
stub midiStreamProperty
stub midiStreamRestart
stub midiStreamStop
stub mixerClose
stub mixerGetControlDetailsA
stub mixerGetControlDetailsW
stub mixerGetDevCapsA
stub mixerGetDevCapsW
stub mixerGetID
stub mixerGetLineControlsA
stub mixerGetLineControlsW
stub mixerGetLineInfoA
stub mixerGetLineInfoW
stub mixerGetNumDevs
stub mixerMessage
stub mixerOpen
stub mixerSetControlDetails
stub mmDrvInstall
stub mmGetCurrentTask
stub mmTaskBlock
stub mmTaskCreate
stub mmTaskSignal
stub mmTaskYield
stub mmioAdvance
stub mmioAscend
stub mmioClose
stub mmioCreateChunk
stub mmioDescend
stub mmioFlush
stub mmioGetInfo
stub mmioInstallIOProcA
stub mmioInstallIOProcW
stub mmioOpenA
stub mmioOpenW
stub mmioRead
stub mmioRenameA
stub mmioRenameW
stub mmioSeek
stub mmioSendMessage
stub mmioSetBuffer
stub mmioSetInfo
stub mmioStringToFOURCCA
stub mmioStringToFOURCCW
stub mmioWrite
stub mmsystemGetVersion
stub sndPlaySoundA
stub sndPlaySoundW
stub timeBeginPeriod
stub timeEndPeriod
stub timeGetDevCaps
stub timeGetSystemTime
stub timeGetTime
stub timeKillEvent
stub timeSetEvent
stub waveInAddBuffer
stub waveInClose
stub waveInGetDevCapsA
stub waveInGetDevCapsW
stub waveInGetErrorTextA
stub waveInGetErrorTextW
stub waveInGetID
stub waveInGetNumDevs
stub waveInGetPosition
stub waveInMessage
stub waveInOpen
stub waveInPrepareHeader
stub waveInReset
stub waveInStart
stub waveInStop
stub waveInUnprepareHeader
stub waveOutBreakLoop
stub waveOutClose
stub waveOutGetDevCapsA
stub waveOutGetDevCapsW
stub waveOutGetErrorTextA
stub waveOutGetErrorTextW
stub waveOutGetID
stub waveOutGetNumDevs
stub waveOutGetPitch
stub waveOutGetPlaybackRate
stub waveOutGetPosition
stub waveOutGetVolume
stub waveOutMessage
stub waveOutOpen
stub waveOutPause
stub waveOutPrepareHeader
stub waveOutReset
stub waveOutRestart
stub waveOutSetPitch
stub waveOutSetPlaybackRate
stub waveOutSetVolume
stub waveOutUnprepareHeader
stub waveOutWrite

END
